"""initial schema

Revision ID: 46c8dd298aaa
Revises: 
Create Date: 2026-09-01 22:34:29.739911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c8dd298aaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datasets',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'analyzing', 'completed', 'failed')", name='ck_datasets_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Numeric(), nullable=True),
    sa.Column('ml_task', sa.Text(), nullable=True),
    sa.Column('ml_target', sa.Text(), nullable=True),
    sa.Column('model_accuracy', sa.Numeric(), nullable=True),
    sa.Column('model_r2_score', sa.Numeric(), nullable=True),
    sa.Column('cleaned_data_uri', sa.Text(), nullable=True),
    sa.Column('model_uri', sa.Text(), nullable=True),
    sa.Column('shap_uri', sa.Text(), nullable=True),
    sa.Column('dashboard_spec_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_analysis_runs_status'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_analysis_runs_dataset_id'), 'analysis_runs', ['dataset_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('run_id', 'type', 'version', name='uq_artifacts_run_type_version')
    )
    op.create_table('column_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.Text(), nullable=False),
    sa.Column('dtype', sa.Text(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('missing_pct', sa.Numeric(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.Column('unique_pct', sa.Numeric(), nullable=True),
    sa.Column('mean', sa.Numeric(), nullable=True),
    sa.Column('std', sa.Numeric(), nullable=True),
    sa.Column('min', sa.Numeric(), nullable=True),
    sa.Column('max', sa.Numeric(), nullable=True),
    sa.Column('q25', sa.Numeric(), nullable=True),
    sa.Column('q50', sa.Numeric(), nullable=True),
    sa.Column('q75', sa.Numeric(), nullable=True),
    sa.Column('top_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_id_column', sa.Boolean(), nullable=False),
    sa.Column('is_datetime', sa.Boolean(), nullable=False),
    sa.Column('has_outliers', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_column_profiles_run_id'), 'column_profiles', ['run_id'], unique=False)
    op.create_table('job_steps',
    sa.Column('job_step_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'skipped')", name='ck_job_steps_status'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('job_step_id'),
    sa.UniqueConstraint('run_id', 'node_name', name='uq_job_steps_run_node')
    )
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('success', 'error')", name='ck_tool_calls_status'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_table('job_steps')
    op.drop_index(op.f('ix_column_profiles_run_id'), table_name='column_profiles')
    op.drop_table('column_profiles')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_analysis_runs_dataset_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('users')
    # ### end Alembic commands ###
